[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -I include
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.filesystem = littlefs
lib_deps =
  ArduinoJson
monitor_dtr = 0
monitor_rts = 0
; Set your board's COM port when flashing (Device Manager on Windows)
; upload_port = COM7
; monitor_port = COM7
